---
- name: Deploy Cluster Logging
  block: 
    - name: Create a temporarily directory
      tempfile:
        state: directory
        suffix: operator
      register: tempfile_1

    - name: Set fact registry credential json file
      set_fact: 
        registry_cred_file: "{{tempfile_1.path}}/cred.json"

    - name: Save credential json file
      copy: 
        content: "{{ registry_auth }}"
        dest: "{{ registry_cred_file }}"

    - name: Create a Namespace for the Cluster Logging Operator
      k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-logging
            annotations:
              openshift.io/node-selector: "" 
            labels:
              openshift.io/cluster-logging: "true"
              openshift.io/cluster-monitoring: "true"
        validate_certs: "{{ k8s_validate_certs | default(true) }} "
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"  
        host: "{{ k8s_api_endpoint }}"            
        state: present

    - name: Get channel version for operator
      k8s_info:
        api_version: packages.operators.coreos.com/v1
        kind: PackageManifest
        name: "{{item}}"
        namespace: openshift-marketplace
        validate_certs: "{{ k8s_validate_certs | default(true) }} "
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"  
        host: "{{ k8s_api_endpoint }}"  
      register: channel_ver
      until: channel_ver.resources is defined and channel_ver.resources | length > 0
      retries: 10
      delay: 60
      with_items:
        - elasticsearch-operator
        - cluster-logging

    - name: Create cluster logging operator group
      k8s:
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: openshift-logging
            namespace: openshift-logging
          spec:
            targetNamespaces:
              - openshift-logging
        validate_certs: "{{ k8s_validate_certs | default(true) }} "
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"            
        host: "{{ k8s_api_endpoint }}"            
        state: present

    - name: Create Subscription object to subscribe a Namespace
      k8s:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: "{{ item.item }}"
            namespace: "{{ 'openshift-logging' if item.item == 'cluster-logging' else 'openshift-operators' }}"
          spec:
            channel: "{{ item.resources[0] | json_query('status.channels[?name != `preview`].name | [0]') }}"
            installPlanApproval: "Automatic"
            name: "{{item.item}}"
            source: "{{item.item}}-catalog"
            sourceNamespace: "openshift-marketplace"
        validate_certs: "{{ k8s_validate_certs | default(true) }} "
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"            
        host: "{{ k8s_api_endpoint }}"            
        state: present
      loop: "{{ channel_ver.results }}"
      loop_control:
        label: "{{item.item}}"

    - name: Create a cluster logging instance
      k8s:
        definition: "{{ logging_cr }}"
        validate_certs: "{{ k8s_validate_certs | default(true) }} "   
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"            
        host: "{{ k8s_api_endpoint }}"            
        state: present
      retries: 10
      delay: 60

  always:   
    - name: Clean up temporarily directory
      file:
        path: "{{ tempfile_1 }}"
        state: absent
      when: tempfile_1 is defined
